### ISSUE TITLE
2 proměnné na stejné adrese

### ISSUE THREAD

**Issue by tuslm** [tuslm/FJP_super_language#20]
2 proměnné se ukládají na stejnou adresu.

viz příklad testcycles.sll  ( i < ahoj )

**Comment by tuslm** [comment]
pravděpodobně za to může úroveň v které se proměnné vytvářejí, proměnné uvnitř cyklu používají vlastní číslování adres (pak se přepisují)

**Comment by BobrZlosyn** [comment]
Mělo by být opraveno
